# Generated by Django 3.1.2 on 2021-10-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_invoice_invoice_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
