# Generated by Django 3.1.2 on 2021-10-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
